import React, { useState, FormEvent } from 'react';
import { Project, Sprint } from '../types';
// FIX: Import CheckSquareIcon for the complete sprint button.
import { PlusIcon, LoaderCircleIcon, StarIcon, TrashIcon, XIcon, CheckSquareIcon } from './Icons';
import { useConfirmation } from '../App';

interface SprintsPageProps {
    project: Project;
    // FIX: The type for new sprint data should not include properties that are auto-generated by the database, like `status`.
    onAddSprint: (sprintData: Omit<Sprint, 'id' | 'projectId' | 'createdAt' | 'status' | 'isDefault'> & { isDefault?: boolean }) => Promise<Sprint>;
    onUpdateSprint: (sprintId: string, updates: Partial<Sprint>) => Promise<void>;
    onDeleteSprint: (sprintId: string) => Promise<void>;
    // FIX: Add the missing onCompleteSprint prop to allow completing a sprint from this page.
    onCompleteSprint: (sprint: Sprint) => void;
}

const EditableField: React.FC<{
  value: string | null;
  onSave: (value: string) => void;
  isTextArea?: boolean;
  placeholder?: string;
  type?: string;
  className?: string;
}> = ({ value, onSave, isTextArea = false, placeholder, type = 'text', className = '' }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [currentValue, setCurrentValue] = useState(value || '');

  const handleSave = () => {
    if (currentValue.trim() !== (value || '').trim()) {
      onSave(currentValue.trim());
    }
    setIsEditing(false);
  };
  
  if (isEditing) {
    return isTextArea ? (
        <textarea
            value={currentValue}
            onChange={(e) => setCurrentValue(e.target.value)}
            onBlur={handleSave}
            placeholder={placeholder}
            className={`w-full bg-[#1C2326] border border-gray-700 rounded-md text-white text-xs p-2 ${className}`}
            rows={3}
            autoFocus
        />
    ) : (
        <input
            type={type}
            value={currentValue}
            onChange={(e) => setCurrentValue(e.target.value)}
            onBlur={handleSave}
            onKeyDown={(e) => e.key === 'Enter' && handleSave()}
            placeholder={placeholder}
            className={`w-full bg-[#1C2326] border border-gray-700 rounded-md text-white p-2 ${className}`}
            autoFocus
        />
    );
  }
  
  return (
    <div onClick={() => setIsEditing(true)} className={`cursor-pointer hover:bg-gray-800/50 rounded-md p-2 -m-2 min-h-[36px] ${className}`}>
        {value || <span className="text-gray-500 italic">{placeholder}</span>}
    </div>
  )
};


export const SprintsPage: React.FC<SprintsPageProps> = ({ project, onAddSprint, onUpdateSprint, onDeleteSprint, onCompleteSprint }) => {
    const [isAdding, setIsAdding] = useState(false);
    const [newSprintName, setNewSprintName] = useState('');
    const requestConfirmation = useConfirmation();

    const handleAddSprint = async (e: FormEvent) => {
        e.preventDefault();
        if (!newSprintName.trim()) return;
        setIsAdding(true);
        try {
            await onAddSprint({
                name: newSprintName.trim(),
                goal: null,
                startDate: null,
                endDate: null,
            });
            setNewSprintName('');
        } catch (error) {
            console.error("Failed to add sprint:", error);
        } finally {
            setIsAdding(false);
        }
    };
    
    const handleSetDefault = (sprint: Sprint) => {
        if (sprint.isDefault) return;
        requestConfirmation({
            title: "Set Default Sprint",
            message: <>Are you sure you want to set <strong>"{sprint.name}"</strong> as the default sprint for new tasks?</>,
            onConfirm: () => onUpdateSprint(sprint.id, { isDefault: true }),
            confirmText: "Set as Default"
        });
    };

    const handleDelete = (sprint: Sprint) => {
        requestConfirmation({
            title: "Delete Sprint",
            message: <>Are you sure you want to delete the sprint <strong>"{sprint.name}"</strong>? Tasks in this sprint will become unsprinted.</>,
            onConfirm: () => onDeleteSprint(sprint.id),
            confirmText: "Delete"
        });
    };
    
    return (
        <div className="max-w-[1000px] mx-auto animate-in fade-in duration-700">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
                <div>
                    <h3 className="text-xl font-bold text-white tracking-tight">Iterative <span className="text-gray-500">Sprints</span></h3>
                    <p className="text-[10px] text-gray-500 uppercase tracking-widest mt-1 font-black">Velocity & Milestone Tracking</p>
                </div>
            </div>
            
            <div className="bg-[#131C1B]/60 backdrop-blur-xl p-5 rounded-2xl border border-white/5 mb-8 shadow-2xl">
                <h4 className="text-[9px] font-black uppercase tracking-[0.2em] text-emerald-500 mb-4">Initialize Iteration</h4>
                <form onSubmit={handleAddSprint} className="flex items-center gap-3">
                    <div className="relative flex-grow group">
                        <PlusIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-600 group-focus-within:text-emerald-500 transition-colors" />
                        <input
                            type="text"
                            value={newSprintName}
                            onChange={(e) => setNewSprintName(e.target.value)}
                            placeholder="NAME YOUR SPHERE..."
                            className="w-full pl-10 pr-4 py-2.5 border border-white/5 rounded-xl bg-white/5 text-white text-[11px] font-bold uppercase tracking-widest focus:outline-none focus:border-emerald-500/30 focus:bg-white/[0.08] transition-all placeholder:text-gray-700"
                            required
                        />
                    </div>
                    <button type="submit" disabled={isAdding} className="px-6 py-2.5 bg-white text-black font-black rounded-xl shadow-xl hover:scale-105 active:scale-95 disabled:bg-gray-700 disabled:text-gray-400 disabled:cursor-not-allowed flex items-center gap-2 text-[10px] uppercase tracking-widest transition-all">
                        {isAdding ? <LoaderCircleIcon className="w-4 h-4 animate-spin"/> : <PlusIcon className="w-4 h-4" />}
                        {isAdding ? 'Syncing...' : 'Deploy'}
                    </button>
                </form>
            </div>

            <div className="space-y-4">
                {project.sprints.length > 0 ? project.sprints.map(sprint => (
                    <div key={sprint.id} className="bg-[#131C1B]/80 backdrop-blur-xl p-6 rounded-2xl border border-white/5 shadow-2xl group/card hover:border-white/10 transition-colors">
                        <div className="flex justify-between items-start gap-8">
                            <div className="flex-grow space-y-5">
                                <div className="flex items-center gap-3">
                                    <div className="w-2 h-8 rounded-full bg-emerald-500/20 group-hover/card:bg-emerald-500 transition-colors" />
                                    <EditableField
                                        value={sprint.name}
                                        onSave={(name) => onUpdateSprint(sprint.id, { name })}
                                        className="font-black text-xs text-white uppercase tracking-widest"
                                        placeholder="Sprint Designation"
                                    />
                                </div>
                                <div className="grid grid-cols-2 gap-6">
                                    <div className="space-y-1.5">
                                        <label className="text-[9px] font-black uppercase tracking-widest text-gray-600 px-1">Synapse Start</label>
                                        <EditableField value={sprint.startDate} onSave={(startDate) => onUpdateSprint(sprint.id, { startDate })} type="date" className="text-white text-[11px] font-bold bg-white/5 rounded-lg px-3 py-2 border border-white/5" />
                                    </div>
                                    <div className="space-y-1.5">
                                        <label className="text-[9px] font-black uppercase tracking-widest text-gray-600 px-1">Termination Date</label>
                                        <EditableField value={sprint.endDate} onSave={(endDate) => onUpdateSprint(sprint.id, { endDate })} type="date" className="text-white text-[11px] font-bold bg-white/5 rounded-lg px-3 py-2 border border-white/5" />
                                    </div>
                                </div>
                                <div className="space-y-1.5 pt-2">
                                    <label className="text-[9px] font-black uppercase tracking-widest text-gray-600 px-1">Neural Objective</label>
                                    <EditableField value={sprint.goal} onSave={(goal) => onUpdateSprint(sprint.id, { goal })} isTextArea placeholder="Define the core objective for this cycle..." className="text-white text-[11px] font-medium bg-white/5 rounded-lg px-3 py-2 border border-white/5 leading-relaxed" />
                                </div>
                            </div>
                            <div className="flex flex-col items-end gap-3 flex-shrink-0">
                                <button
                                    onClick={() => handleSetDefault(sprint)}
                                    disabled={sprint.isDefault}
                                    className={`flex items-center gap-2 px-4 py-2 text-[8px] font-black uppercase tracking-[0.2em] rounded-xl transition-all shadow-xl ${sprint.isDefault ? 'bg-emerald-500 text-black' : 'bg-white/5 text-gray-500 hover:text-white hover:bg-white/10'}`}
                                >
                                    <StarIcon className={`w-3.5 h-3.5 ${sprint.isDefault ? 'fill-current' : ''}`} />
                                    {sprint.isDefault ? 'Primary' : 'Set Primary'}
                                </button>
                                <div className="flex items-center gap-2">
                                    <button
                                        onClick={() => onCompleteSprint(sprint)}
                                        disabled={sprint.status === 'completed'}
                                        className={`flex items-center gap-2 px-4 py-2 text-[8px] font-black uppercase tracking-[0.2em] rounded-xl transition-all shadow-xl ${sprint.status === 'completed' ? 'bg-white/5 text-gray-700 cursor-not-allowed' : 'bg-blue-600/10 text-blue-400 hover:bg-blue-600 hover:text-white'}`}
                                    >
                                        <CheckSquareIcon className="w-3.5 h-3.5" />
                                        {sprint.status === 'completed' ? 'SYNCHRONIZED' : 'TERMINATE'}
                                    </button>
                                    <button
                                        onClick={() => handleDelete(sprint)}
                                        className="p-2.5 text-gray-600 hover:text-red-400 hover:bg-red-500/10 border border-transparent hover:border-red-500/20 rounded-xl transition-all"
                                    >
                                        <TrashIcon className="w-4 h-4" />
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                )) : (
                    <div className="text-center py-24 bg-white/5 rounded-3xl border border-dashed border-white/10">
                        <LoaderCircleIcon className="mx-auto h-12 w-12 text-gray-800 mb-4" />
                        <p className="text-sm font-black text-white uppercase tracking-[0.2em]">No Iterations Detected</p>
                        <p className="text-[10px] text-gray-600 mt-2 uppercase tracking-widest">Initialize a new sprint to begin velocity tracking.</p>
                    </div>
                )}
            </div>
        </div>
    );
};
