import React, { useState, useMemo } from 'react';
import { AiGeneratedTaskFromFile, TaskPriority, Sprint } from '../types';
import { XIcon, LoaderCircleIcon } from './Icons';

interface TaskConfirmationModalProps {
    tasks: AiGeneratedTaskFromFile[];
    sprints: Sprint[];
    onConfirm: (sprintId: string | null) => Promise<void>;
    onCancel: () => void;
}

const priorityStyles: Record<TaskPriority, string> = {
  [TaskPriority.URGENT]: 'bg-gray-200 text-black font-bold',
  [TaskPriority.HIGH]: 'bg-gray-400 text-black',
  [TaskPriority.MEDIUM]: 'bg-gray-600 text-white',
  [TaskPriority.LOW]: 'bg-gray-800 text-gray-400',
};

export const TaskConfirmationModal: React.FC<TaskConfirmationModalProps> = ({ tasks, sprints, onConfirm, onCancel }) => {
    const [isCreating, setIsCreating] = useState(false);
    
    const defaultSprintId = useMemo(() => {
        const defaultSprint = (sprints || []).find(s => s.isDefault);
        return defaultSprint ? defaultSprint.id : '';
    }, [sprints]);
    
    const [selectedSprintId, setSelectedSprintId] = useState<string>(defaultSprintId);

    const handleConfirm = async () => {
        setIsCreating(true);
        try {
            await onConfirm(selectedSprintId || null);
        } finally {
            // The parent will close the modal on success, but we should stop loading anyway.
            setIsCreating(false);
        }
    };
    
    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-40 flex items-center justify-center p-4" onClick={onCancel}>
            <div className="bg-[#131C1B] rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col" onClick={(e) => e.stopPropagation()}>
                <header className="p-4 border-b border-gray-800 flex justify-between items-center flex-shrink-0">
                    <div>
                        <h2 className="text-lg font-bold text-white">Confirm New Tasks</h2>
                        <p className="text-sm text-gray-400">Review the tasks generated by AI from your file.</p>
                    </div>
                    <button onClick={onCancel} className="p-2 rounded-full text-gray-400 hover:bg-gray-800 transition-colors">
                        <XIcon className="w-6 h-6" />
                    </button>
                </header>

                <div className="p-6 overflow-y-auto custom-scrollbar space-y-3">
                    <div className="mb-4">
                        <label htmlFor="sprint-select" className="block text-sm font-medium text-white mb-1">Assign to Sprint</label>
                        <select
                            id="sprint-select"
                            value={selectedSprintId}
                            onChange={(e) => setSelectedSprintId(e.target.value)}
                            className="w-full px-3 py-2 border border-gray-800 rounded-md shadow-sm focus:outline-none focus:ring-gray-500 focus:border-gray-500 bg-[#1C2326] text-white text-sm"
                        >
                            <option value="">No Sprint</option>
                            {(sprints || []).map(sprint => (
                                <option key={sprint.id} value={sprint.id}>{sprint.name}</option>
                            ))}
                        </select>
                    </div>

                    {tasks.map((task, index) => (
                        <div key={index} className="bg-[#1C2326]/50 p-3 rounded-md">
                            <div className="flex justify-between items-start gap-2">
                                <p className="font-semibold text-sm text-white">{task.title}</p>
                                <div className="flex items-center gap-2 flex-shrink-0">
                                    <span className="text-xs font-medium bg-gray-800 text-gray-400 px-2 py-1 rounded-full">{task.status}</span>
                                    <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${priorityStyles[task.priority]}`}>{task.priority}</span>
                                </div>
                            </div>
                            <p className="text-xs text-gray-400 mt-1">{task.description}</p>
                        </div>
                    ))}
                </div>

                <footer className="p-4 border-t border-gray-800 flex justify-end gap-3 flex-shrink-0">
                    <button type="button" onClick={onCancel} className="px-4 py-2 bg-gray-700 text-white font-semibold rounded-lg hover:bg-gray-600 text-sm">
                        Cancel
                    </button>
                    <button onClick={handleConfirm} disabled={isCreating} className="px-4 py-2 bg-gray-300 text-black font-semibold rounded-lg shadow-md hover:bg-gray-400 disabled:bg-gray-500 disabled:cursor-not-allowed flex items-center gap-2 text-sm">
                        {isCreating && <LoaderCircleIcon className="w-5 h-5 animate-spin" />}
                        {isCreating ? 'Creating Tasks...' : `Create ${tasks.length} Tasks`}
                    </button>
                </footer>
            </div>
        </div>
    );
};
